baseURL = "/"
languageCode = "en-us"
title = "JAMStack Themes"
theme = "jamstackthemes"
paginate = 3
enableGitInfo = true

[taxonomies]
  ssg =  "ssg"
  cms = "cms"
  tag = "tags"

[params]
    google_analytics_id = ""

[outputs]
  home = ["HTML","RSS", "JSON"]
  section = ["HTML","RSS", "JSON"]